name: CI/CD Pipeline for Admin Panel

on:
  push:
    branches:
      - main    # Trigger the workflow on push to the 'main' branch
  pull_request:
    branches:
      - main    # Trigger the workflow on PRs targeting the 'main' branch



